apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iamroles-v1alpha1-configmap
  namespace: system
data:
  #iam.policy.action.prefix.whitelist: "s3:,sts:,ec2:Describe,acm:Describe,acm:List,acm:Get,route53:Get,route53:List,route53:Create,route53:Delete,route53:Change,kms:Decrypt,kms:Encrypt,kms:ReEncrypt,kms:GenerateDataKey,kms:DescribeKey,dynamodb:,secretsmanager:GetSecretValue,es:,sqs:SendMessage,sqs:ReceiveMessage,sqs:DeleteMessage,SNS:Publish,sqs:GetQueueAttributes,sqs:GetQueueUrl"
  #iam.policy.resource.blacklist: "kops"
  #iam.policy.s3.restricted.resource: "*"
  aws.accountId: "461168169469"
  aws.MasterRole: "iam-operator-role-test"
  #iam.managed.policies: "shared.cluster.k8s.local"